name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      
      - name: Install packages
        run: yarn install
      
      - name: Generate code for subgraph
        run: yarn codegen
      
      - name: Build subgraph
        run: yarn build

      - name: Deploy subgraph
        if: ${{ github.event_name == 'push' }}
        env: 
          GRAPH_TOKEN: ${{ secrets.GRAPH_TOKEN }}
        run: yarn deploy $GRAPH_TOKEN